# Generated by Django 5.2.1 on 2025-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la especialidad o servicio (ej. Medicina, Laboratorio)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(choices=[('principal', 'Servicio Médico Principal'), ('secundario', 'Servicio Médico Secundario (Derivación)')], default='principal', help_text='Indica si el servicio es principal (se puede agendar cita) o secundario (solo por derivación).', max_length=10)),
            ],
            options={
                'verbose_name': 'Especialidad Médica o Servicio',
                'verbose_name_plural': 'Especialidades Médicas y Servicios',
            },
        ),
    ]
