# Generated by Django 5.2.1 on 2025-05-29 02:34

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_institucional',
            field=models.EmailField(help_text='Correo institucional de la universidad', max_length=254, unique=True, validators=[usuarios.models.validate_unsch_email]),
        ),
    ]
