# Generated by Django 5.2.1 on 2025-06-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_correo_institucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='escuela_profesional',
            field=models.CharField(choices=[('ADMINISTRACION_EMPRESAS', 'Administración de Empresas'), ('AGRONOMIA', 'Agronomía'), ('ANTROPOLOGIA', 'Antropología'), ('ARQUEOLOGIA_HISTORIA', 'Arqueología e Historia'), ('BIOLOGIA', 'Biología'), ('CIENCIAS_COMUNICACION', 'Ciencias de la Comunicación'), ('CIENCIAS_FISICOMATEMATICAS', 'Ciencias Físico-Matemáticas'), ('CONTABILIDAD_AUDITORIA', 'Contabilidad y Auditoría'), ('DERECHO', 'Derecho'), ('ECONOMIA', 'Economía'), ('EDUCACION FISICA', 'Educación Física'), ('EDUCACION_INICIAL', 'Educación Inicial'), ('EDUCACION_PRIMARIA', 'Educación Primaria'), ('EDUCACION_SECUNDARIA', 'Educación Secundaria'), ('ENFERMERIA', 'Enfermería'), ('FARMACIA_BIOQUIMICA', 'Farmacia y Bioquímica'), ('ING_AGROFORESTAL', 'Ingeniería Agroforestal'), ('ING_AGROINDUSTRIAL', 'Ingeniería Agroindustrial'), ('ING_AGRICOLA', 'Ingeniería Agrícola'), ('ING_CIVIL', 'Ingeniería Civil'), ('ING_MINAS', 'Ingeniería de Minas'), ('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_ALIMENTARIAS', 'Ingeniería en Industrias Alimentarias'), ('ING_QUIMICA', 'Ingeniería Química'), ('MEDICINA_HUMANA', 'Medicina Humana'), ('MEDICINA_VETERINARIA', 'Medicina Veterinaria'), ('OBSTETRICIA', 'Obstetricia'), ('TRABAJO_SOCIAL', 'Trabajo Social')], max_length=100),
        ),
    ]
