# Generated by Django 5.2.1 on 2025-05-29 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_solicitadas', to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='cita',
            name='personal_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='usuarios.personalsalud'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='cita_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='servicio_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones_recibidas', to='servicios.especialidadmedica'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('especialidad', 'fecha', 'hora_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='derivacion',
            unique_together={('cita_origen', 'servicio_destino')},
        ),
    ]
