# Generated by Django 5.2.1 on 2025-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], default='Pendiente', max_length=20),
        ),
    ]
